steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/polar-valor-386820/frontend-chess:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/polar-valor-386820/frontend-chess:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'chess-cluster', '--zone', 'europe-southwest1-a', '--project', 'polar-valor-386820']
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=europe-southwest1-a', 'CLOUDSDK_CONTAINER_CLUSTER=chess-cluster']
  args: ['rollout', 'restart', 'deployment/frontend-chess']
images: ['gcr.io/polar-valor-386820/frontend-chess:latest']
