apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      name: vue-app
      namespace: chess
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: cebridani/frontend-chess:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: chess
spec:
  type: NodePort
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30044