apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-chess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-chess
  template:
    metadata:
      labels:
        app: frontend-chess
    spec:
      containers:
      - name: frontend-chess
        image: gcr.io/polar-valor-386820/frontend-chess:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-chess-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend-chess
