apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-chess
  namespace: chess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-chess
  template:
    metadata:
      name: frontend-chess
      namespace: chess
      labels:
        app: frontend-chess
    spec:
      containers:
        - name: frontend-chess
          image: cebridani/frontend-chess:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-chess
  namespace: chess
spec:
  selector:
    app: frontend-chess
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
