apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-chess-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-chess
  template:
    metadata:
      labels:
        app: frontend-chess
    spec:
      containers:
        - name: frontend-chess
          image: gcr.io/polar-valor-386820/frontend-chess:v1
          ports:
            - containerPort: 8080
