apiVersion: v1
kind: Service
metadata:
  name: frontend-chess-service
spec:
  selector:
    app: frontend-chess
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
